### PR TITLE
Add DataDumpAliases

### PR DESCRIPTION
**Pull request by Universal-Omega**

### CODE REVIEW

**Comment by dmehus** [comment]
I don't see what the alias special page is in [this commit](https://github.com/miraheze/DataDump/pull/13/commits/4dca440be8fc2517d47d452ac44e37699cbaaaf9). Special:DataDump //is// the special page. Can you clarify what this commit and PR aims to do?

**Comment by Universal-Omega** [comment]
> I don't see what the alias special page is in [this commit](https://github.com/miraheze/DataDump/pull/13/commits/4dca440be8fc2517d47d452ac44e37699cbaaaf9). Special:DataDump //is// the special page. Can you clarify what this commit and PR aims to do?

Special:DataDump is what it is. This is per https://phabricator.miraheze.org/T6675

**Comment by dmehus** [comment]
> > I don't see what the alias special page is in [this commit](https://github.com/miraheze/DataDump/pull/13/commits/4dca440be8fc2517d47d452ac44e37699cbaaaf9). Special:DataDump //is// the special page. Can you clarify what this commit and PR aims to do?
> 
> Special:DataDump is what it is. This is per https://phabricator.miraheze.org/T6675

@Universal-Omega, ah excellent. So this adds support "DataDump" to be translated. Does it create a new interface message to translate this?

**Comment by Universal-Omega** [comment]
> > > I don't see what the alias special page is in [this commit](https://github.com/miraheze/DataDump/pull/13/commits/4dca440be8fc2517d47d452ac44e37699cbaaaf9). Special:DataDump //is// the special page. Can you clarify what this commit and PR aims to do?
> > 
> > 
> > Special:DataDump is what it is. This is per https://phabricator.miraheze.org/T6675
> 
> @Universal-Omega, ah excellent. So this adds support "DataDump" to be translated. Does it create a new interface message to translate this?

To my knowledge, no it won't, it will need to be translated directly on the repo.

**Comment by dmehus** [comment]
> > > > I don't see what the alias special page is in [this commit](https://github.com/miraheze/DataDump/pull/13/commits/4dca440be8fc2517d47d452ac44e37699cbaaaf9). Special:DataDump //is// the special page. Can you clarify what this commit and PR aims to do?
> > > 
> > > 
> > > Special:DataDump is what it is. This is per https://phabricator.miraheze.org/T6675
> > 
> > 
> > @Universal-Omega, ah excellent. So this adds support "DataDump" to be translated. Does it create a new interface message to translate this?
> 
> To my knowledge, no it won't, it will need to be translated directly on the repo.
@Universal-Omega Ah, this just adds support to be able to translate the special page via PRs in the repository. That's fine. Perhaps we should create a 'radar'-type Phabricator task, though, to explore adding on-wiki translation functionality? I have seen extension-added special pages translated via extension-added MediaWiki interface messages

**Pull request merged**
